### POST request to example server
POST http://localhost:4000/patients
Content-Type: application/json

{
  "name": "John Doe",
  "email": "test222@example.com",
  "address": "123 main street",
  "dateOfBirth": "1995-09-09",
  "registeredDate": "2025-03-01"
}

###